// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qzuyutklullrypjkgdze.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6dXl1dGtsdWxscnlwamtnZHplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMjMzNDksImV4cCI6MjA1ODY5OTM0OX0.QnCAwPpeV7SY5soEysoUvbBgBLX0zbtFaKyghv31Pi4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);